// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRPyS1WXID770EaCJFQQXKHMGdf_3doUk',
    appId: '1:820337923914:android:2da27ee1a5ac937c56d3b3',
    messagingSenderId: '820337923914',
    projectId: 'homesync-a1d20',
    storageBucket: 'homesync-a1d20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGg5kMmJugDA3DME5k6QIvsnSD0MuezE',
    appId: '1:820337923914:ios:a4ff4134172e24ea56d3b3',
    messagingSenderId: '820337923914',
    projectId: 'homesync-a1d20',
    storageBucket: 'homesync-a1d20.firebasestorage.app',
    iosBundleId: 'com.sncmlife.homesync',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu54KiqeideCBUFC6-CgUMWsTRi1-ncmU',
    appId: '1:820337923914:web:9e08951c8fad291156d3b3',
    messagingSenderId: '820337923914',
    projectId: 'homesync-a1d20',
    authDomain: 'homesync-a1d20.firebaseapp.com',
    storageBucket: 'homesync-a1d20.firebasestorage.app',
  );
}
